"""Phase 1, UI-independent benchmark recorder engine."""

from .database import EngineDatabase
from .reporting import ReportingService
from .services import BenchmarkService, CatalogService
from .statistics import (
    BenchmarkRunGroupBy,
    BenchmarkRunStatistics,
    BenchmarkRunStatisticsFilters,
    BenchmarkRunStatisticsGroup,
    BenchmarkRunStatisticsSummary,
    BenchmarkStatisticsFilters,
    BenchmarkStatisticsSummary,
    CategoricalDistribution,
    NumericSummary,
    ScoreboardGroupBy,
    ScoreboardEntryStatisticsFilters,
    ScoreboardStatistics,
    ScoreboardStatisticsFilters,
    ScoreboardStatisticsGroup,
    ScoreboardStatisticsSummary,
    StatisticsService,
    TimeBucketGranularity,
    TimeBucketResult,
    TimeBucketSummary,
    TimeBucketValue,
    build_time_buckets,
    categorical_distribution,
    numeric_summary,
    time_bucket_for,
)

__all__ = (
    "BenchmarkRunGroupBy",
    "BenchmarkRunStatistics",
    "BenchmarkRunStatisticsFilters",
    "BenchmarkRunStatisticsGroup",
    "BenchmarkRunStatisticsSummary",
    "BenchmarkService",
    "BenchmarkStatisticsFilters",
    "BenchmarkStatisticsSummary",
    "CategoricalDistribution",
    "categorical_distribution",
    "CatalogService",
    "EngineDatabase",
    "NumericSummary",
    "ReportingService",
    "ScoreboardGroupBy",
    "ScoreboardEntryStatisticsFilters",
    "ScoreboardStatistics",
    "ScoreboardStatisticsFilters",
    "ScoreboardStatisticsGroup",
    "ScoreboardStatisticsSummary",
    "StatisticsService",
    "TimeBucketGranularity",
    "TimeBucketResult",
    "TimeBucketSummary",
    "TimeBucketValue",
    "build_time_buckets",
    "numeric_summary",
    "time_bucket_for",
)
