"""Explicit Add/Edit dialog for PromptTemplate records."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import replace
from typing import Any

from PySide6.QtWidgets import QCheckBox, QComboBox, QLabel, QLineEdit, QPlainTextEdit, QWidget

from ..context import GuiApplicationContext

try:
    from ...engine.domain import BENCHMARK_TYPES, PromptTemplate
except ImportError:  # pragma: no cover - exercised by top-level test imports.
    from engine.domain import BENCHMARK_TYPES, PromptTemplate  # type: ignore[no-redef]

from .benchmark_editor import BENCHMARK_TYPE_LABELS
from .base import CatalogEditorDialog


class PromptTemplateEditorDialog(CatalogEditorDialog):
    """Edit prompt metadata and exact multiline text without exposing its hash input."""

    def __init__(
        self,
        context: GuiApplicationContext,
        template: PromptTemplate | None = None,
        parent: QWidget | None = None,
        *,
        confirm_close: Callable[[], bool] | None = None,
    ) -> None:
        self.template = template
        super().__init__(
            context,
            title="Edit Prompt Template" if template is not None else "Add Prompt Template",
            parent=parent,
            confirm_close=confirm_close,
        )
        self.setAccessibleName("Edit Prompt Template" if template is not None else "Add Prompt Template")

        self.name_edit = self._line(template.name if template else "", "Prompt template name", "Required")
        self.version_edit = self._line(template.version if template else "", "Prompt template version", "Required")
        self.prompt_text_edit = QPlainTextEdit(template.prompt_text if template else "")
        self.prompt_text_edit.setAccessibleName("Prompt template text")
        self.prompt_text_edit.setMinimumHeight(220)
        self.prompt_text_edit.setToolTip("Whitespace and line breaks are stored exactly as entered.")

        self.type_combo = QComboBox()
        self.type_combo.setAccessibleName("Prompt template benchmark type")
        for value in BENCHMARK_TYPES:
            self.type_combo.addItem(BENCHMARK_TYPE_LABELS.get(value, value), value)
        if template is not None:
            index = self.type_combo.findData(template.benchmark_type)
            if index >= 0:
                self.type_combo.setCurrentIndex(index)

        self.notes_edit = QPlainTextEdit(template.notes if template else "")
        self.notes_edit.setAccessibleName("Prompt template notes")
        self.notes_edit.setMinimumHeight(96)

        self.active_checkbox = QCheckBox("Active and available to Add Run")
        self.active_checkbox.setAccessibleName("Prompt template active")
        self.active_checkbox.setChecked(template.is_active if template else True)

        self.prompt_hash_value = QLabel(template.prompt_hash if template else "Generated by the engine when saved")
        self.prompt_hash_value.setObjectName("promptHashValue")
        self.prompt_hash_value.setAccessibleName("Prompt template hash")
        self.prompt_hash_value.setWordWrap(True)
        self.prompt_hash_value.setToolTip("The engine derives this SHA-256 value from the exact UTF-8 prompt text.")

        self.form.addRow("Name *", self.name_edit)
        self.form.addRow("Version *", self.version_edit)
        self.form.addRow("Prompt text *", self.prompt_text_edit)
        self.form.addRow("Benchmark type *", self.type_combo)
        self.form.addRow("Notes", self.notes_edit)
        self.form.addRow("Lifecycle", self.active_checkbox)
        self.form.addRow("Prompt hash", self.prompt_hash_value)

        for field in (self.name_edit, self.version_edit):
            field.textChanged.connect(self.mark_dirty)
        self.register_field("name", self.name_edit)
        self.register_field("version", self.version_edit)
        self.register_field("prompt_text", self.prompt_text_edit)
        self.register_field("benchmark_type", self.type_combo)
        self.prompt_text_edit.textChanged.connect(self.mark_dirty)
        self.type_combo.currentIndexChanged.connect(self.mark_dirty)
        self.notes_edit.textChanged.connect(self.mark_dirty)
        self.active_checkbox.toggled.connect(self.mark_dirty)

    @staticmethod
    def _line(value: str, accessible_name: str, placeholder: str = "") -> QLineEdit:
        field = QLineEdit(value)
        field.setAccessibleName(accessible_name)
        if placeholder:
            field.setPlaceholderText(placeholder)
        return field

    def build_draft(self) -> PromptTemplate:
        values: dict[str, Any] = dict(
            name=self.name_edit.text(),
            version=self.version_edit.text(),
            prompt_text=self.prompt_text_edit.toPlainText(),
            # The service derives this value; the editor never accepts a hash input.
            prompt_hash=self.template.prompt_hash if self.template is not None else "",
            benchmark_type=str(self.type_combo.currentData() or ""),
            notes=self.notes_edit.toPlainText(),
            is_active=self.active_checkbox.isChecked(),
        )
        if self.template is not None:
            return replace(self.template, **values)
        return PromptTemplate(**values)

    def save_draft(self, draft: PromptTemplate) -> PromptTemplate:
        if draft.id is None:
            return self.context.catalog.create_prompt_template(draft)
        return self.context.catalog.update_prompt_template(draft)


__all__ = ("PromptTemplateEditorDialog",)
